"""
DISHA Seed Data.
15+ realistic opportunities with edge cases for demo and testing.
Includes the golden demo scenario data.
"""

from __future__ import annotations

from datetime import datetime, timezone, timedelta

NOW = datetime.now(timezone.utc)
NOW_ISO = NOW.isoformat()


def _future_date(days: int) -> str:
    return (NOW + timedelta(days=days)).strftime("%d %b %Y")


def _past_date(days: int) -> str:
    return (NOW - timedelta(days=days)).strftime("%d %b %Y")


# ── Golden Demo Student Profile ──────────────────────────────

DEMO_STUDENT_PROFILE = {
    "user_id": "demo-user-001",
    "display_name": "Alex Kumar",
    "academic_year": 2,
    "degree_type": "B.Tech",
    "institution": "National Institute of Technology",
    "career_goal": "AI/ML Engineer",
    "interests": ["AI", "Machine Learning", "Sustainability", "Open Source"],
    "availability": "weekends",
    "budget": "free",
    "preferred_format": "remote",
    "location": "India",
    "experience_level": "intermediate",
    "sustainability_interest": True,
    "skills": [
        {"name": "Java", "level": "intermediate", "category": "programming"},
        {"name": "Python", "level": "intermediate", "category": "programming"},
        {"name": "Basic ML", "level": "beginner", "category": "ai"},
        {"name": "Machine Learning", "level": "beginner", "category": "ai"},
        {"name": "Web Development", "level": "beginner", "category": "web"},
        {"name": "HTML/CSS", "level": "intermediate", "category": "web"},
        {"name": "Git", "level": "intermediate", "category": "tools"},
    ],
    "allow_eligibility_check": True,
    "allow_team_visibility": True,
    "allow_external_scraping": False,
}


# ── Seed Opportunities (15 with edge cases) ──────────────────

SEED_OPPORTUNITIES = [
    # 1. Golden demo: Completely valid, high match
    {
        "id": "opp-001",
        "title": "AI for Sustainable Cities Hackathon",
        "description": "Build AI-powered solutions for urban sustainability challenges. Use machine learning to address SDG 11 targets including smart transportation, energy efficiency, and waste management.",
        "organizer": "Global Climate Tech Initiative",
        "source_url": "https://climatetechhack.org/ai-sustainable-cities-2026",
        "source_name": "Official Organizer Website",
        "theme": "AI/ML",
        "start_date": _future_date(35),
        "end_date": _future_date(37),
        "application_deadline": _future_date(30),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 3,
        "team_size_max": 5,
        "eligibility_text": "Open to undergraduate and postgraduate students worldwide",
        "eligibility_structured": {
            "academic_year": ["undergraduate", "postgraduate"],
            "degree_type": ["B.Tech", "B.Sc", "M.Tech", "M.Sc"],
            "nationality": ["International"],
        },
        "required_skills": ["Python", "Machine Learning"],
        "preferred_skills": ["TensorFlow", "Docker", "FastAPI", "Data Visualization"],
        "experience_level": "beginner",
        "sustainability_tags": ["Climate Action", "Smart Cities"],
        "sdg_tags": [{"sdg_id": 11, "label": "SDG 11", "reason": "Sustainable cities and communities", "evidence": "Event focuses on urban sustainability solutions"}],
        "application_url": "https://climatetechhack.org/apply",
        "status": "active",
        "trust_score": 92,
        "access_score": 95,
        "last_verified_at": (NOW - timedelta(minutes=18)).isoformat(),
        "sources_count": 3,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"prize_pool": "$10,000", "mentorship": True},
    },
    # 2. High trust, hybrid format
    {
        "id": "opp-002",
        "title": "Open Source Contributor Summit 2026",
        "description": "A two-day summit celebrating open source contributions. Includes workshops on Git workflows, code review practices, and community building. Great networking opportunities.",
        "organizer": "OSF Foundation",
        "source_url": "https://osfsummit.org/2026",
        "source_name": "OSF Foundation Official",
        "theme": "Open Source",
        "start_date": _future_date(42),
        "end_date": _future_date(43),
        "application_deadline": _future_date(35),
        "format": "Hybrid",
        "location": "San Francisco, CA",
        "is_remote": False,
        "cost": "Free",
        "currency": None,
        "team_size_min": None,
        "team_size_max": None,
        "eligibility_text": "Open to all developers and students",
        "eligibility_structured": {
            "academic_year": ["undergraduate", "postgraduate", "professional"],
        },
        "required_skills": ["Git", "Programming"],
        "preferred_skills": ["Open Source", "Linux", "Documentation"],
        "experience_level": "any",
        "sustainability_tags": ["Education"],
        "sdg_tags": [{"sdg_id": 4, "label": "SDG 4", "reason": "Quality education through open knowledge", "evidence": "Open source education and collaboration"}],
        "application_url": "https://osfsummit.org/register",
        "status": "active",
        "trust_score": 98,
        "access_score": 75,
        "last_verified_at": (NOW - timedelta(hours=2)).isoformat(),
        "sources_count": 4,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 3. Low trust, unknown eligibility, paid
    {
        "id": "opp-003",
        "title": "FinTech App Challenge",
        "description": "Design and build innovative fintech applications. Participants will work on real-world financial inclusion problems.",
        "organizer": "National Bank",
        "source_url": "https://example-bank.com/fintech-challenge",
        "source_name": "Bank Website",
        "theme": "FinTech",
        "start_date": _future_date(55),
        "end_date": _future_date(57),
        "application_deadline": _future_date(50),
        "format": "In-Person",
        "location": "Mumbai, India",
        "is_remote": False,
        "cost": "₹500",
        "currency": "INR",
        "team_size_min": 2,
        "team_size_max": 4,
        "eligibility_text": None,
        "eligibility_structured": None,
        "required_skills": ["Python", "Financial APIs", "React"],
        "preferred_skills": ["Blockchain", "UPI"],
        "experience_level": "intermediate",
        "sustainability_tags": [],
        "sdg_tags": [],
        "application_url": "https://example-bank.com/apply",
        "status": "active",
        "trust_score": 65,
        "access_score": 40,
        "last_verified_at": (NOW - timedelta(days=5)).isoformat(),
        "sources_count": 1,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 4. Missing deadline
    {
        "id": "opp-004",
        "title": "Global Data Science Challenge",
        "description": "Analyze real-world datasets to solve pressing global issues. Compete with data scientists from around the world.",
        "organizer": "DataSci Foundation",
        "source_url": "https://datasci-challenge.org/global",
        "source_name": "DataSci Foundation",
        "theme": "Data Science",
        "start_date": _future_date(60),
        "end_date": None,
        "application_deadline": None,
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 1,
        "team_size_max": 3,
        "eligibility_text": "Open to students and professionals",
        "eligibility_structured": {
            "academic_year": ["undergraduate", "postgraduate", "professional"],
        },
        "required_skills": ["Python", "Pandas", "Statistics"],
        "preferred_skills": ["R", "Tableau", "SQL"],
        "experience_level": "intermediate",
        "sustainability_tags": ["Data for Good"],
        "sdg_tags": [],
        "application_url": "https://datasci-challenge.org/register",
        "status": "active",
        "trust_score": 78,
        "access_score": 85,
        "last_verified_at": (NOW - timedelta(days=3)).isoformat(),
        "sources_count": 2,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 5. Contradictory deadline (will be used with evidence)
    {
        "id": "opp-005",
        "title": "Cybersecurity CTF Championship",
        "description": "Capture The Flag competition testing offensive and defensive cybersecurity skills. Real-world vulnerability assessment and incident response.",
        "organizer": "CyberSec Alliance",
        "source_url": "https://cybersec-alliance.com/ctf-2026",
        "source_name": "CyberSec Alliance",
        "theme": "Cybersecurity",
        "start_date": _future_date(45),
        "end_date": _future_date(46),
        "application_deadline": _future_date(38),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 2,
        "team_size_max": 4,
        "eligibility_text": "Open to all students aged 18-30",
        "eligibility_structured": {
            "age_range": {"min": 18, "max": 30},
            "academic_year": ["undergraduate", "postgraduate"],
        },
        "required_skills": ["Networking", "Linux", "Python"],
        "preferred_skills": ["Cryptography", "Reverse Engineering", "Web Security"],
        "experience_level": "intermediate",
        "sustainability_tags": [],
        "sdg_tags": [],
        "application_url": "https://cybersec-alliance.com/register",
        "status": "active",
        "trust_score": 82,
        "access_score": 80,
        "last_verified_at": (NOW - timedelta(hours=6)).isoformat(),
        "sources_count": 2,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"has_contradiction": True},
    },
    # 6. Duplicate of opp-001 (different source)
    {
        "id": "opp-006",
        "title": "AI for Sustainable Cities Hackathon 2026",
        "description": "Join the Global Climate Tech Initiative's flagship hackathon. Build ML solutions for smart cities and sustainability.",
        "organizer": "Global Climate Tech Initiative",
        "source_url": "https://devfolio.co/hackathons/ai-sustainable-cities",
        "source_name": "Devfolio",
        "theme": "AI/ML",
        "start_date": _future_date(35),
        "end_date": _future_date(37),
        "application_deadline": _future_date(30),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 3,
        "team_size_max": 5,
        "eligibility_text": "Open to undergraduate students",
        "eligibility_structured": {
            "academic_year": ["undergraduate"],
        },
        "required_skills": ["Python", "Machine Learning"],
        "preferred_skills": ["TensorFlow", "Docker"],
        "experience_level": "beginner",
        "sustainability_tags": ["Climate"],
        "sdg_tags": [{"sdg_id": 11, "label": "SDG 11", "reason": "Sustainable cities", "evidence": "Focus on urban sustainability"}],
        "application_url": "https://devfolio.co/hackathons/ai-sustainable-cities/apply",
        "status": "active",
        "trust_score": 90,
        "access_score": 95,
        "last_verified_at": (NOW - timedelta(hours=1)).isoformat(),
        "sources_count": 1,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"is_duplicate_of": "opp-001"},
    },
    # 7. Expired opportunity
    {
        "id": "opp-007",
        "title": "Summer AI Research Internship",
        "description": "8-week research internship focused on NLP and computer vision applications. Stipend provided.",
        "organizer": "AI Research Lab, IIT Delhi",
        "source_url": "https://airlab.iitd.ac.in/summer-intern",
        "source_name": "IIT Delhi",
        "theme": "AI/ML",
        "start_date": _past_date(30),
        "end_date": _past_date(1),
        "application_deadline": _past_date(60),
        "format": "In-Person",
        "location": "New Delhi, India",
        "is_remote": False,
        "cost": "Free",
        "currency": None,
        "team_size_min": None,
        "team_size_max": None,
        "eligibility_text": "3rd/4th year B.Tech students only",
        "eligibility_structured": {
            "academic_year": ["3", "4"],
            "degree_type": ["B.Tech"],
        },
        "required_skills": ["Python", "Deep Learning", "PyTorch"],
        "preferred_skills": ["NLP", "Computer Vision", "Research Papers"],
        "experience_level": "advanced",
        "sustainability_tags": [],
        "sdg_tags": [{"sdg_id": 4, "label": "SDG 4", "reason": "Quality education", "evidence": "Research internship"}],
        "application_url": None,
        "status": "expired",
        "trust_score": 95,
        "access_score": 50,
        "last_verified_at": _past_date(2),
        "sources_count": 2,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"stipend": "₹25,000/month"},
    },
    # 8. Skill gap challenge
    {
        "id": "opp-008",
        "title": "Cloud-Native MLOps Challenge",
        "description": "Design and deploy production-grade ML pipelines using Kubernetes, Docker, and cloud services.",
        "organizer": "CloudTech Community",
        "source_url": "https://cloudtech.dev/mlops-challenge",
        "source_name": "CloudTech Community",
        "theme": "DevOps",
        "start_date": _future_date(28),
        "end_date": _future_date(29),
        "application_deadline": _future_date(21),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 2,
        "team_size_max": 3,
        "eligibility_text": "Open to all skill levels",
        "eligibility_structured": None,
        "required_skills": ["Docker", "Kubernetes", "Python", "ML", "CI/CD"],
        "preferred_skills": ["Terraform", "AWS", "MLflow"],
        "experience_level": "advanced",
        "sustainability_tags": [],
        "sdg_tags": [],
        "application_url": "https://cloudtech.dev/mlops-challenge/register",
        "status": "active",
        "trust_score": 80,
        "access_score": 70,
        "last_verified_at": (NOW - timedelta(days=1)).isoformat(),
        "sources_count": 1,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 9. Beginner-friendly
    {
        "id": "opp-009",
        "title": "First-Time Hacker Weekend",
        "description": "A beginner-friendly hackathon designed for students who have never participated in a hackathon before. Mentorship and workshops included.",
        "organizer": "HackForAll Foundation",
        "source_url": "https://hackforall.org/first-time",
        "source_name": "HackForAll Foundation",
        "theme": "General Tech",
        "start_date": _future_date(20),
        "end_date": _future_date(21),
        "application_deadline": _future_date(15),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 1,
        "team_size_max": 4,
        "eligibility_text": "Open to all undergraduate students. No prior hackathon experience required.",
        "eligibility_structured": {
            "academic_year": ["undergraduate"],
            "custom_requirements": ["No prior hackathon experience required"],
        },
        "required_skills": [],
        "preferred_skills": ["Any Programming Language"],
        "experience_level": "beginner",
        "sustainability_tags": ["Education", "Inclusion"],
        "sdg_tags": [{"sdg_id": 4, "label": "SDG 4", "reason": "Quality education", "evidence": "Beginner-focused education event"}],
        "application_url": "https://hackforall.org/first-time/apply",
        "status": "active",
        "trust_score": 88,
        "access_score": 100,
        "last_verified_at": (NOW - timedelta(hours=3)).isoformat(),
        "sources_count": 2,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"mentorship_available": True},
    },
    # 10. Remote-only, paid
    {
        "id": "opp-010",
        "title": "Web3 Development Bootcamp",
        "description": "Intensive 4-week bootcamp on Ethereum, Solidity, and decentralized application development.",
        "organizer": "BlockLearn Academy",
        "source_url": "https://blocklearn.io/web3-bootcamp",
        "source_name": "BlockLearn Academy",
        "theme": "Web3/Blockchain",
        "start_date": _future_date(14),
        "end_date": _future_date(42),
        "application_deadline": _future_date(10),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "₹2,999",
        "currency": "INR",
        "team_size_min": None,
        "team_size_max": None,
        "eligibility_text": "Basic programming knowledge required",
        "eligibility_structured": {
            "custom_requirements": ["Basic programming knowledge required"],
        },
        "required_skills": ["JavaScript", "Git"],
        "preferred_skills": ["Solidity", "React"],
        "experience_level": "intermediate",
        "sustainability_tags": [],
        "sdg_tags": [],
        "application_url": "https://blocklearn.io/web3-bootcamp/enroll",
        "status": "active",
        "trust_score": 72,
        "access_score": 55,
        "last_verified_at": (NOW - timedelta(days=4)).isoformat(),
        "sources_count": 1,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 11. Sustainability tagged, social impact
    {
        "id": "opp-011",
        "title": "Tech for Rural Education Hackathon",
        "description": "Build technology solutions that improve educational access in rural India. Focus on low-bandwidth, offline-first solutions.",
        "organizer": "EduReach India",
        "source_url": "https://edureach.in/hackathon-2026",
        "source_name": "EduReach India",
        "theme": "Social Impact",
        "start_date": _future_date(25),
        "end_date": _future_date(26),
        "application_deadline": _future_date(20),
        "format": "Hybrid",
        "location": "Bangalore, India",
        "is_remote": False,
        "cost": "Free",
        "currency": None,
        "team_size_min": 3,
        "team_size_max": 5,
        "eligibility_text": "Open to all Indian undergraduate and postgraduate students",
        "eligibility_structured": {
            "academic_year": ["undergraduate", "postgraduate"],
            "nationality": ["India"],
        },
        "required_skills": ["Python", "Web Development"],
        "preferred_skills": ["React", "Flutter", "Offline-First Design"],
        "experience_level": "any",
        "sustainability_tags": ["Rural Education", "Digital Inclusion"],
        "sdg_tags": [
            {"sdg_id": 4, "label": "SDG 4", "reason": "Quality education", "evidence": "Directly targets rural education access"},
            {"sdg_id": 10, "label": "SDG 10", "reason": "Reduced inequalities", "evidence": "Addresses digital divide in rural areas"},
        ],
        "application_url": "https://edureach.in/hackathon-2026/apply",
        "status": "active",
        "trust_score": 85,
        "access_score": 72,
        "last_verified_at": (NOW - timedelta(hours=5)).isoformat(),
        "sources_count": 2,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"travel_reimbursement": True},
    },
    # 12. Team-based, advanced
    {
        "id": "opp-012",
        "title": "Autonomous Drone Racing League",
        "description": "Build autonomous drone navigation software. Teams compete in simulated and real-world drone racing challenges.",
        "organizer": "DroneX Labs",
        "source_url": "https://dronexlabs.com/racing-league",
        "source_name": "DroneX Labs",
        "theme": "Robotics/AI",
        "start_date": _future_date(50),
        "end_date": _future_date(52),
        "application_deadline": _future_date(40),
        "format": "In-Person",
        "location": "Hyderabad, India",
        "is_remote": False,
        "cost": "₹1,000",
        "currency": "INR",
        "team_size_min": 4,
        "team_size_max": 6,
        "eligibility_text": "Engineering students with robotics experience",
        "eligibility_structured": {
            "degree_type": ["B.Tech", "M.Tech"],
            "custom_requirements": ["Robotics or embedded systems experience recommended"],
        },
        "required_skills": ["Python", "ROS", "Computer Vision", "Embedded Systems"],
        "preferred_skills": ["C++", "SLAM", "PID Controllers"],
        "experience_level": "advanced",
        "sustainability_tags": [],
        "sdg_tags": [{"sdg_id": 9, "label": "SDG 9", "reason": "Industry, innovation and infrastructure", "evidence": "Autonomous systems innovation"}],
        "application_url": "https://dronexlabs.com/racing-league/register",
        "status": "active",
        "trust_score": 75,
        "access_score": 30,
        "last_verified_at": (NOW - timedelta(days=2)).isoformat(),
        "sources_count": 1,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 13. Incomplete source data
    {
        "id": "opp-013",
        "title": "University Innovation Challenge",
        "description": None,
        "organizer": None,
        "source_url": "https://unknown-college.edu/innovation",
        "source_name": "College Notice Board",
        "theme": None,
        "start_date": None,
        "end_date": None,
        "application_deadline": _future_date(25),
        "format": None,
        "location": None,
        "is_remote": None,
        "cost": None,
        "currency": None,
        "team_size_min": None,
        "team_size_max": None,
        "eligibility_text": None,
        "eligibility_structured": None,
        "required_skills": [],
        "preferred_skills": [],
        "experience_level": None,
        "sustainability_tags": [],
        "sdg_tags": [],
        "application_url": None,
        "status": "unverified",
        "trust_score": 25,
        "access_score": None,
        "last_verified_at": None,
        "sources_count": 1,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
    # 14. Climate & sustainability, free
    {
        "id": "opp-014",
        "title": "Green Code Sprint — Climate Data Visualization",
        "description": "Use open climate datasets to build compelling data visualizations that communicate climate change impact. Best visualizations will be featured in the UN Climate Report.",
        "organizer": "Climate Data Collective",
        "source_url": "https://climatedata.org/green-code-sprint",
        "source_name": "Climate Data Collective",
        "theme": "Data Science",
        "start_date": _future_date(18),
        "end_date": _future_date(19),
        "application_deadline": _future_date(14),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 1,
        "team_size_max": 3,
        "eligibility_text": "Open to all students and early-career professionals",
        "eligibility_structured": {
            "academic_year": ["undergraduate", "postgraduate", "professional"],
        },
        "required_skills": ["Python", "Data Visualization"],
        "preferred_skills": ["D3.js", "Matplotlib", "Plotly", "Climate Science"],
        "experience_level": "beginner",
        "sustainability_tags": ["Climate Action", "Data for Good"],
        "sdg_tags": [
            {"sdg_id": 13, "label": "SDG 13", "reason": "Climate action", "evidence": "Directly addresses climate data communication"},
        ],
        "application_url": "https://climatedata.org/green-code-sprint/apply",
        "status": "active",
        "trust_score": 90,
        "access_score": 92,
        "last_verified_at": (NOW - timedelta(hours=1)).isoformat(),
        "sources_count": 3,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {"un_partnership": True},
    },
    # 15. Web development, intermediate
    {
        "id": "opp-015",
        "title": "Full Stack Web Dev Championship",
        "description": "Build a complete web application from scratch in 48 hours. Judged on functionality, design, code quality, and presentation.",
        "organizer": "WebDev Arena",
        "source_url": "https://webdevarena.com/championship-2026",
        "source_name": "WebDev Arena",
        "theme": "Web Development",
        "start_date": _future_date(22),
        "end_date": _future_date(23),
        "application_deadline": _future_date(18),
        "format": "Online / Remote",
        "location": None,
        "is_remote": True,
        "cost": "Free",
        "currency": None,
        "team_size_min": 1,
        "team_size_max": 2,
        "eligibility_text": "Open to all developers",
        "eligibility_structured": None,
        "required_skills": ["JavaScript", "HTML/CSS", "React"],
        "preferred_skills": ["Next.js", "TypeScript", "Tailwind CSS", "Node.js"],
        "experience_level": "intermediate",
        "sustainability_tags": [],
        "sdg_tags": [],
        "application_url": "https://webdevarena.com/championship-2026/register",
        "status": "active",
        "trust_score": 83,
        "access_score": 88,
        "last_verified_at": (NOW - timedelta(hours=8)).isoformat(),
        "sources_count": 2,
        "created_at": NOW_ISO,
        "updated_at": NOW_ISO,
        "metadata": {},
    },
]


# ── Seed Evidence (for golden demo opportunity) ──────────────

SEED_EVIDENCE = [
    {
        "id": "ev-001",
        "opportunity_id": "opp-001",
        "field_name": "application_deadline",
        "extracted_value": _future_date(30),
        "source_url": "https://climatetechhack.org/ai-sustainable-cities-2026",
        "source_name": "Official Organizer Website",
        "snippet": f"...applications close on {_future_date(30)}. Late submissions will not be accepted...",
        "extracted_at": NOW_ISO,
        "confidence": 0.96,
    },
    {
        "id": "ev-002",
        "opportunity_id": "opp-001",
        "field_name": "cost",
        "extracted_value": "Free",
        "source_url": "https://devfolio.co/hackathons/ai-sustainable-cities",
        "source_name": "Devfolio",
        "snippet": "...registration is completely free for all participants...",
        "extracted_at": NOW_ISO,
        "confidence": 0.98,
    },
    {
        "id": "ev-003",
        "opportunity_id": "opp-001",
        "field_name": "format",
        "extracted_value": "Online",
        "source_url": "https://college-board.edu/opportunities/ai-hackathon",
        "source_name": "College Notice Board",
        "snippet": "...this is a fully online event, participate from anywhere...",
        "extracted_at": NOW_ISO,
        "confidence": 0.94,
    },
    {
        "id": "ev-004",
        "opportunity_id": "opp-001",
        "field_name": "eligibility",
        "extracted_value": "Open to undergraduate and postgraduate students worldwide",
        "source_url": "https://climatetechhack.org/ai-sustainable-cities-2026",
        "source_name": "Official Organizer Website",
        "snippet": "...open to undergraduate and postgraduate students from any university worldwide...",
        "extracted_at": NOW_ISO,
        "confidence": 0.95,
    },
    {
        "id": "ev-005",
        "opportunity_id": "opp-001",
        "field_name": "prize",
        "extracted_value": None,
        "source_url": None,
        "source_name": None,
        "snippet": None,
        "extracted_at": NOW_ISO,
        "confidence": 0.0,
    },
    # Evidence for contradictory opportunity (opp-005)
    {
        "id": "ev-006",
        "opportunity_id": "opp-005",
        "field_name": "application_deadline",
        "extracted_value": _future_date(38),
        "source_url": "https://cybersec-alliance.com/ctf-2026",
        "source_name": "CyberSec Alliance",
        "snippet": f"...deadline for registration: {_future_date(38)}...",
        "extracted_at": NOW_ISO,
        "confidence": 0.90,
    },
    {
        "id": "ev-007",
        "opportunity_id": "opp-005",
        "field_name": "application_deadline",
        "extracted_value": _future_date(35),
        "source_url": "https://college-events.com/cybersec-ctf",
        "source_name": "College Events Portal",
        "snippet": f"...register before {_future_date(35)} to secure your spot...",
        "extracted_at": NOW_ISO,
        "confidence": 0.85,
    },
]


# ── Seed Sources ─────────────────────────────────────────────

SEED_SOURCES = [
    {"id": "src-001", "opportunity_id": "opp-001", "source_url": "https://climatetechhack.org/ai-sustainable-cities-2026", "source_name": "Official Organizer Website", "credibility_score": 95, "fetched_at": NOW_ISO},
    {"id": "src-002", "opportunity_id": "opp-001", "source_url": "https://devfolio.co/hackathons/ai-sustainable-cities", "source_name": "Devfolio", "credibility_score": 90, "fetched_at": NOW_ISO},
    {"id": "src-003", "opportunity_id": "opp-001", "source_url": "https://college-board.edu/opportunities/ai-hackathon", "source_name": "College Notice Board", "credibility_score": 70, "fetched_at": NOW_ISO},
    {"id": "src-004", "opportunity_id": "opp-005", "source_url": "https://cybersec-alliance.com/ctf-2026", "source_name": "CyberSec Alliance", "credibility_score": 85, "fetched_at": NOW_ISO},
    {"id": "src-005", "opportunity_id": "opp-005", "source_url": "https://college-events.com/cybersec-ctf", "source_name": "College Events Portal", "credibility_score": 65, "fetched_at": NOW_ISO},
]


# ── Seed Team Candidates ─────────────────────────────────────

SEED_TEAM_CANDIDATES = [
    {
        "user_id": "user-sarah-001",
        "display_name": "Sarah J.",
        "career_goal": "UX Designer",
        "interests": ["Design", "AI", "Sustainability"],
        "availability": "weekends",
        "skills": [
            {"name": "React", "level": "advanced"},
            {"name": "Figma", "level": "advanced"},
            {"name": "Tailwind CSS", "level": "advanced"},
            {"name": "TypeScript", "level": "intermediate"},
            {"name": "User Research", "level": "intermediate"},
        ],
    },
    {
        "user_id": "user-rahul-001",
        "display_name": "Rahul M.",
        "career_goal": "Data Scientist",
        "interests": ["Data Science", "AI", "Climate"],
        "availability": "weekends",
        "skills": [
            {"name": "Python", "level": "advanced"},
            {"name": "Pandas", "level": "advanced"},
            {"name": "Research", "level": "intermediate"},
            {"name": "Statistics", "level": "intermediate"},
            {"name": "Data Visualization", "level": "intermediate"},
        ],
    },
    {
        "user_id": "user-priya-001",
        "display_name": "Priya S.",
        "career_goal": "Cloud Engineer",
        "interests": ["DevOps", "Cloud", "Sustainability"],
        "availability": "flexible",
        "skills": [
            {"name": "Docker", "level": "advanced"},
            {"name": "AWS", "level": "intermediate"},
            {"name": "Kubernetes", "level": "intermediate"},
            {"name": "Python", "level": "intermediate"},
            {"name": "CI/CD", "level": "intermediate"},
        ],
    },
]


# ── Seed Planner Events ──────────────────────────────────────

SEED_PLANNER_EVENTS = [
    {
        "id": "plan-001",
        "user_id": "demo-user-001",
        "title": "Docker Workshop",
        "event_type": "learning",
        "event_date": _future_date(32),
        "time": "10:00 AM",
    },
    {
        "id": "plan-002",
        "user_id": "demo-user-001",
        "title": "AI Hackathon Starts",
        "event_type": "opportunity",
        "event_date": _future_date(35),
        "end_date": _future_date(37),
        "time": "09:00 AM",
        "opportunity_id": "opp-001",
    },
    {
        "id": "plan-003",
        "user_id": "demo-user-001",
        "title": "Mid-Semester Exam",
        "event_type": "academic",
        "event_date": _future_date(36),
        "time": "10:00 AM",
    },
]
